//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Console.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string Hostname {
            get {
                return ((string)(this["Hostname"]));
            }
            set {
                this["Hostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Configured {
            get {
                return ((bool)(this["Configured"]));
            }
            set {
                this["Configured"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>_spschema_tb</string>
  <string>_tableschema_tb</string>
  <string>spschema_tb</string>
  <string>tableschema_tb</string>
  <string>achievement_clear_tb</string>
  <string>achievement_tb</string>
  <string>character_delete_tb</string>
  <string>quest_daily_list_tb</string>
  <string>quest_daily_tb</string>
  <string>skill_active_tb</string>
  <string>skill_passive_tb</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IgnoreList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IgnoreList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>Table Description: No Description</string>\r\n  <string>Table Description: L" +
            "ist of Schemas.</string>\r\n  <string>Table Description: List of Table Schemas.</s" +
            "tring>\r\n  <string>Table Description: List of Database error codes.</string>\r\n  <" +
            "string>Table Description: List of Achievement IDs.</string>\r\n  <string>Table Des" +
            "cription: List of Costume IDs.</string>\r\n  <string>Table Description: No Descrip" +
            "tion</string>\r\n  <string>Table Description: List of Item IDs.</string>\r\n  <strin" +
            "g>Table Description: List of Quest IDs.</string>\r\n  <string>Table Description: L" +
            "ist of Skill IDs.</string>\r\n  <string>Table Description: List of Stage IDs. (Sta" +
            "ge = Map)</string>\r\n  <string>Table Description: List of Schemas.</string>\r\n  <s" +
            "tring>Table Description: List of Table Schemas.</string>\r\n  <string>Table Descri" +
            "ption: List of Departments which can be used to quickly identify staff accounts." +
            "</string>\r\n  <string>Table Description: user_tb for Andriod/IOS accounts.</strin" +
            "g>\r\n  <string>Table Description: Lists ID Number for Andriod/IOS, used in device" +
            "_tb to identify account platform.</string>\r\n  <string>Table Description: List of" +
            " Banned accounts.</string>\r\n  <string>Table Description: Might be a list of Acco" +
            "untTypes for account_tb. Current admin accounts are ID 2</string>\r\n  <string>Tab" +
            "le Description: List of Accounts sent from user_tb.</string>\r\n  <string>Table De" +
            "scription: List of schemas/database.</string>\r\n  <string>Table Description: List" +
            " of schemas/database types, used by db_tb.</string>\r\n  <string>Table Description" +
            ": List of Database login details.</string>\r\n  <string>Table Description: List of" +
            " Nation UIDs, not sure where this is used yet but most likely in some account da" +
            "tabase.</string>\r\n  <string>Table Description: Patch URL used by Client, Maybe u" +
            "sed to verify Client &amp; Server match.</string>\r\n  <string>Table Description: " +
            "Revision/Patch Number and World List for Client.</string>\r\n  <string>Table Descr" +
            "iption: List of Device Types, used in account_tb to identify the platform the ac" +
            "count uses to play.</string>\r\n  <string>Table Description: List of Server UIDs a" +
            "nd there corresponding Database type.</string>\r\n  <string>Table Description: Lis" +
            "t of Servers.</string>\r\n  <string>Table Description: List of Server types, used " +
            "by server_tb.</string>\r\n  <string>Table Description: List of World Servers.</str" +
            "ing>\r\n  <string>Table Description: List of BlackIron for each Character.</string" +
            ">\r\n  <string>Table Description: List of Rewards for each Character.</string>\r\n  " +
            "<string>Table Description: List of Accounts sent from either user_tb or account_" +
            "tb in Front Database.</string>\r\n  <string>Table Description: List of Achievement" +
            " IDs to be removed from a Character.</string>\r\n  <string>Table Description: List" +
            " of every Achievements obtained by players.</string>\r\n  <string>Table Descriptio" +
            "n: List of deleted Characters.</string>\r\n  <string>Table Description: List of Ch" +
            "aracters.</string>\r\n  <string>Table Description: List of every Costume obtained " +
            "by players.</string>\r\n  <string>Table Description: List of every Item in game an" +
            "d what character owns said item and where it\'s being stored.</string>\r\n  <string" +
            ">Table Description: List of every Jewel in game and what character owns said jew" +
            "el item and where it\'s being stored.</string>\r\n  <string>Table Description: List" +
            " of every Mastery in game and what character owns said mastery item and where it" +
            "\'s being stored.</string>\r\n  <string>Table Description: List of every Item in ga" +
            "me and what character owns said item.</string>\r\n  <string>Table Description: Lis" +
            "t of every Item that has been deleted.</string>\r\n  <string>Table Description: Lo" +
            "oks like a way to give extra options to items?</string>\r\n  <string>Table Descrip" +
            "tion: List of Items with their Reinforce Level.</string>\r\n  <string>Table Descri" +
            "ption: List of Items with their Smelting Level.</string>\r\n  <string>Table Descri" +
            "ption: List of each item that can be stacked and the amount said item can be sta" +
            "cked to.</string>\r\n  <string>Table Description: List of Items with their TagBuff" +
            " ID.</string>\r\n  <string>Table Description: List of every Item in game.</string>" +
            "\r\n  <string>Table Description: List of Items with their Transcendence Amount.</s" +
            "tring>\r\n  <string>Table Description: List of Item IDs sent via Mail.</string>\r\n " +
            " <string>Table Description: List of Item UIDs sent via Mail.</string>\r\n  <string" +
            ">Table Description: List of Money sent via Mail.</string>\r\n  <string>Table Descr" +
            "iption: List of every Mail sent to and from players.</string>\r\n  <string>Table D" +
            "escription: No Description</string>\r\n  <string>Table Description: No Description" +
            "</string>\r\n  <string>Table Description: List of Daily Quests accepeted by player" +
            "s.</string>\r\n  <string>Table Description: List of Daily Quests accepeted by play" +
            "ers then sent to quest_daily_list_tb.</string>\r\n  <string>Table Description: Lis" +
            "t of Main Quests accepeted by players.</string>\r\n  <string>Table Description: No" +
            " Description</string>\r\n  <string>Table Description: List of Weekly Quests accepe" +
            "ted by players.</string>\r\n  <string>Table Description: List of Weekly Quests acc" +
            "epeted by players then sent to quest_weekly_list_tb.</string>\r\n  <string>Table D" +
            "escription: List of Active Skills for each Player.</string>\r\n  <string>Table Des" +
            "cription: List of Passive Skills for each Player.</string>\r\n  <string>Table Desc" +
            "ription: List of Treasure obtained by each Player.</string>\r\n  <string>Table Des" +
            "cription: Maybe a list of what players have completed the Tutorial?</string>\r\n  " +
            "<string>Table Description: No Description</string>\r\n  <string>Table Description:" +
            " List of Vehicles obtained by Players and their Reinforce Level.</string>\r\n  <st" +
            "ring>Table Description: Maybe a list of Waypoints used by each player, Auto play" +
            " maybe?</string>\r\n  <string>Table Description: Raw list of accounts, used for re" +
            "gistration and login/verification. Then sent to account_tb.</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection TableDescription {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TableDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int TableDescriptionCount {
            get {
                return ((int)(this["TableDescriptionCount"]));
            }
        }
    }
}
