type BloodSets =
  | 'Muscle Strength Manual'
  | 'Nine Yin Manual'
  | 'Nine Yang Manual'
  | 'Violet Mist Art'
  | 'Northern Profound Art'
  | 'Toad Stance'

type BloodNames =
  | 'Sky Palace'
  | 'Royal Decree'
  | 'Pulsing Sky'
  | 'Great Ruler'
  | "Land's End"
  | 'Centenary Congregation'
  | 'Embroidered Throne'
  | 'Golden Jade'
  | 'Heart Core'
  | 'Virtuous Elevation'
  | 'Antirelaxation'
  | 'Springwater'
  | 'Pinnacle Star'
  | 'Wind Hub'
  | 'Great Union'
  | 'Earth Valley'
  | 'Dubhe'
  | 'Fertile Scale'
  | 'Mizar'
  | 'Alkaid'
  | 'Divisive Action'
  | 'Waterbridge'
  | 'United Heaven'
  | 'Quorum'
